config/routes.rb
Rails.application.routes.draw do
  
devise_for :users 
  

  resources :skills do
    collection do
      get 'search'
    end
    
    resources :reviews, except: [:show, :index, :destroy]
  end

  root to: "skills#index"

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	searchkick
	belongs_to :user
	has_many :reviews
	has_attached_file :avatar, styles: { medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :skills
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_skill
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
    
  end
  def show
    @review = Review.find(params[:id])
  end
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.skill_id = @skill.id

    if @review.save
      redirect_to @skill
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_skill
      @skill = Skill.find(params[:skill_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /skills
  # GET /skills.json
  def search
    if params[:search].present?
      @skills = Skill.search(params[:search])
    else
      @skills= Skill.all
    end
  end
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @reviews = Review.where(skill_id: @skill.id).order("created_at DESC")
  end

  # GET /skills/new
  def new
    @skill = current_user.skills.build
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = current_user.skills.build(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:title, :description, :experience, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JiahaoLink", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Add Skills", new_skill_path, class: "active" %></li>
          <li><%= link_to "Edit My Account", edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_skills_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jiahaolink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@skill, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>


<%= link_to 'Back', skill_path(@skill) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_path(@skill) %>

app/views/skills/_form.html.erb
<%= form_for @skill, html: { multipart: true } do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_area :experience %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Welcome to JiahaoLink</h1>
    <p>We believe that if we try hard enough, this world would be a better place for all of us.</p>
    <p><%= link_to "Sign Up To Join JiahaoLink", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @skills.each do |skill| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag skill.avatar.url(:medium), class: 'image'), skill %>
        
      </div>
    </div>
  <% end %>
</div>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/search.html.erb
<div class="row">
  <% @skills.each do |skill| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag skill.avatar.url(:medium), class: 'image'), skill %>
      </div>
    </div>
  <% end %>
</div>

app/views/skills/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			 <div class="col-md-4">
			 	<%= image_tag @skill.avatar.url(:medium) %>
			 	<div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @skill.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @skill.description %></td>
              </tr>
              
              <tr>
                <td><strong>Experience:</strong></td>
                <td><%= @skill.experience %></td>
              </tr>

              <tr>
                <td><strong>User:</strong></td>
                <td><%= @skill.user.email %></td>
              </tr>
            </tbody>
          </table>
       </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @skill.title %></h1>
        <p><%= @skill.description %></p>
        <%= link_to "Write Review", new_skill_review_path(@skill), class: "btn btn-danger" %>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, please tell us about your experience.</h3>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <P><%= review.rating %></p>
               
              <p><%= review.comment %></p>
              

            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div>
<%= link_to 'Delete', skill_path(@skill), method: :delete, data: {confirm: "Are You Sure?"} %> |
<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %> |
</div>